name: Windows Playbook
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook user configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]
